a = [{'flightId': '580654176', 'legType': 'Flight',
      'flight': {'id': '580654176', 'flightNumber': 'CA1509', 'sharedFlightNumber': '', 'sharedFlightName': None,
                 'airlineCode': 'CA', 'airlineName': '中国国航', 'craftTypeCode': '330', 'craftKind': 'L',
                 'craftTypeName': '空中客车 A330', 'craftTypeKindDisplayName': '大型', 'specialCraft': False,
                 'departureAirportInfo': {'cityTlc': 'BJS', 'cityName': '北京', 'airportTlc': 'PEK',
                                          'airportName': '首都国际机场',
                                          'terminal': {'id': 3, 'name': 'T3', 'shortName': 'T3'}},
                 'arrivalAirportInfo': {'cityTlc': 'HGH', 'cityName': '杭州', 'airportTlc': 'HGH',
                                        'airportName': '萧山国际机场',
                                        'terminal': {'id': 29, 'name': 'T1', 'shortName': 'T1'}},
                 'departureDate': '2019-05-03 07:30:00', 'delayedTime': None, 'arrivalDate': '2019-05-03 09:40:00',
                 'comfort': None, 'punctualityRate': '100%', 'mealType': 'Meal', 'oilFee': None, 'tax': None,
                 'durationDays': 0, 'stopTimes': 0, 'stopInfo': None}, 'cabins': [
        {'id': '4605440177', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgEEAEY6IECQICAgICAgICACGgB', 'cabinClass': 'Y', 'priceClass': 'K', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'AirLineMarketing', 'ifFreeDelivery': False,
         'directFlightChannel': 'CA-WS',
         'price': {'compositionPrice': False, 'price': 330, 'salePrice': 330, 'printPrice': 330, 'fdPrice': 550,
                   'rate': 0.14, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 8,
         'provideBillType': 'Itinerary', 'groupType': 'Airline', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CnsIvQcQrREaAwjKAiIGCNitAxgEKgMI9BIyAwjKAjgESgZOb3JtYWxgvQdqEEFpckxpbmVNYXJrZXRpbmdyAkNBegNQRUuCAQNIR0iKAQZDQTE1MDmSAQFLmgEHCMS63xgQAqIBAk5BsAGAgIDAgIGAgAi4AQHCAQNBRFU=',
            'refundFeeFormulaId': None, 'minRefundFee': 297, 'minEndorseFee': 132, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价30%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价60％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价90%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价20%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价35%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价40%的更改费，起飞前4小时（不含）内及起飞后需收取票面价50%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 1}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 500, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 3,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['AirlineMarketing', 'ServicePackageProduct'], 'applyType': 'NA', 'needApply': False,
         'successRate': None, 'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None,
         'normalPolicyReturnCash': None, 'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None,
         'advertXPackage': None, 'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None,
         'productSource': 4, 'childInfantBookAdultInfo': None, 'childPolicy': {'price': 550, 'serviceCharge': None},
         'babyPolicy': None, 'infantSoldOut': False, 'businessAircraftInfo': None, 'displayDefault': True,
         'labels': None, 'additionalProductGroups': [
            {'groupType': 'MultipleChoiceX', 'marketType': '0', 'marketLabel': '0', 'tagCode': '', 'price': 0,
             'rate': 0, 'products': [
                {'id': '3', 'name': '金牌服务包', 'type': 'ServicePackage', 'price': 38, 'printPrice': 90, 'quantity': 1,
                 'selected': True, 'productTypeId': '1', 'productType': '1', 'shuttleType': None,
                 'transferProductToken': None}]}], 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'JPFWB', 'beginKeys': ['JJCZL', 'JPFWB'],
         'limitPolicy': False},
        {'id': '4605440176', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgEEAEY6IECQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'K', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'AirLineMarketing', 'ifFreeDelivery': False,
         'directFlightChannel': 'CA-WS',
         'price': {'compositionPrice': False, 'price': 330, 'salePrice': 330, 'printPrice': 330, 'fdPrice': 550,
                   'rate': 0.14, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 8,
         'provideBillType': 'Itinerary', 'groupType': 'Airline', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CnsIvQcQrREaAwjKAiIGCNitAxgEKgMI9BIyAwjKAjgESgZOb3JtYWxgvQdqEEFpckxpbmVNYXJrZXRpbmdyAkNBegNQRUuCAQNIR0iKAQZDQTE1MDmSAQFLmgEHCMS63xgQAqIBAk5BsAGAgIDAgIGAgAi4AQHCAQNBRFU=',
            'refundFeeFormulaId': None, 'minRefundFee': 297, 'minEndorseFee': 132, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价30%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价60％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价90%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价20%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价35%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价40%的更改费，起飞前4小时（不含）内及起飞后需收取票面价50%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 1}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 500, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 3,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['AirlineMarketing'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 4,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 550, 'serviceCharge': None}, 'babyPolicy': None,
         'infantSoldOut': False, 'businessAircraftInfo': None, 'displayDefault': True, 'labels': None,
         'additionalProductGroups': [
             {'groupType': 'MultipleChoiceX', 'marketType': '0', 'marketLabel': '0', 'tagCode': '', 'price': 0,
              'rate': 0, 'products': [
                 {'id': 'C2C30', 'name': '航空意外险', 'type': 'InsuranceProduct', 'price': 30, 'printPrice': 3200000,
                  'quantity': 1, 'selected': True, 'productTypeId': None, 'productType': None, 'shuttleType': None,
                  'transferProductToken': None},
                 {'id': '413', 'name': '接送机券', 'type': 'ShuttleCoupon', 'price': 18, 'printPrice': 50, 'quantity': 1,
                  'selected': True, 'productTypeId': '258', 'productType': '258', 'shuttleType': None,
                  'transferProductToken': None}]}], 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'JJCZL', 'beginKeys': ['JJCZL', 'YC_ZDJ'],
         'limitPolicy': False},
        {'id': '4605440174', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgBEAEY2K0DQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'K', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'BusinessPriority', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 550, 'salePrice': 550, 'printPrice': 550, 'fdPrice': 550,
                   'rate': 0.23, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 8,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|Cn8IvQcQrREaAwimBCIGCNitAxgEKgMI9BIyBgjYrQMYBDgDSgZOb3JtYWxgvQdqEEJ1c2luZXNzUHJpb3JpdHlyAkNBegNQRUuCAQNIR0iKAQZDQTE1MDmSAQFLmgEHCMS63xgQAqIBA05GRLABgICAwKCBgIAIuAEBwgEDQURV',
            'refundFeeFormulaId': None, 'minRefundFee': 495, 'minEndorseFee': 220, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价30%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价60％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价90%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价20%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价35%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价40%的更改费，起飞前4小时（不含）内及起飞后需收取票面价50%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 500, 'extensionFlags': 0, 'extensionFlags2': 576460795387314200, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['BusinessPriority'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 550, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': True, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'SWYX_LM', 'beginKeys': ['SWYX_LM'],
         'limitPolicy': False},
        {'id': '4605440175', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgEEAEYgNMOQICAgICAgICACA==', 'cabinClass': 'C', 'priceClass': 'R', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'AirLineMarketing', 'ifFreeDelivery': False,
         'directFlightChannel': 'CA-WS',
         'price': {'compositionPrice': False, 'price': 2400, 'salePrice': 2400, 'printPrice': 2400, 'fdPrice': 2420,
                   'rate': 0.34, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 8,
         'provideBillType': 'Itinerary', 'groupType': 'Airline', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CnsIuAcQqBEaAwjgEiIGCNDiDhgEKgMI3DgyAwjgEjgESgZOb3JtYWxguAdqEEFpckxpbmVNYXJrZXRpbmdyAkNBegNQRUuCAQNIR0iKAQZDQTE1MDmSAQFSmgEHCMS63xgQAqIBAk5BsAGAgIDAgIGAgAi4AQHCAQNBRFU=',
            'refundFeeFormulaId': None, 'minRefundFee': 240, 'minEndorseFee': 120, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外收取票面价5%退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价5％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价10%的退票费，起飞前4小时（不含）内及起飞后需收取票面价20%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外同等舱位免费更改，起飞前720小时（不含）内至航班起飞前336小时（含）同等舱位免费更改，起飞前336小时（不含）内至起飞前4小时（含）收取票面价5%的更改费，起飞前4小时（不含）内及起飞后需收取票面价10%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 1}, 'pcCode': '', 'freeLuggageAmount': 30, 'luggageType': 1,
         'accumulateMileage': 1249, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 3,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['AirlineMarketing'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 4,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 2420, 'serviceCharge': None}, 'babyPolicy': None,
         'infantSoldOut': False, 'businessAircraftInfo': None, 'displayDefault': True, 'labels': None,
         'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'HSZX_CCZDJ',
         'beginKeys': ['HSZX_CCZDJ', 'CC_ZDJ'], 'limitPolicy': False},
        {'id': '4605440161', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEY0OIOQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'Y', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 2420, 'salePrice': 2420, 'printPrice': 2420, 'fdPrice': 2420,
                   'rate': 1, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CmoIuQcQqREaAwj0EiIDCPQSKgMI9BIyAwj0EjgDSgZOb3JtYWxguQdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgEBWZoBBwjEut8YEAKiAQJGRLABgICAwICBgIAIuAEBwgEDQURV',
            'refundFeeFormulaId': None, 'minRefundFee': 242, 'minEndorseFee': 0, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外免收退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价5％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价10%的退票费，起飞前4小时（不含）内及起飞后需收取票面价20%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None,
            'endorseNote': '允许签转，如变更后承运人适用票价高于国航票价，需补齐票价差额后进行变更，同时收取变更手续费;如变更后承运人适用票价低于国航票价，可按自愿退票办理.如按照自愿变更办理，差额不退，同时收取变更手续费.',
            'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外同等舱位免费更改；起飞前720小时（不含）内至航班起飞前4小时（含）同等舱位免费更改三次，第四次起每次收取票面价5%的更改费；起飞前4小时（不含）内及起飞后需收取票面价10%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 1249, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 1210, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'YC_QJ', 'beginKeys': ['YC_QJ'],
         'limitPolicy': False},
        {'id': '4605440157', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEY8KcsQICAgICAgICACA==', 'cabinClass': 'C', 'priceClass': 'J', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 7260, 'salePrice': 7260, 'printPrice': 7260, 'fdPrice': 7260,
                   'rate': 1, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CmoItwcQpxEaAwjcOCIDCNw4KgMI3DgyAwjcODgDSgZOb3JtYWxgtwdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgEBSpoBBwjEut8YEAKiAQJGRLABgICAwICBgIAIuAEBwgEDQURV',
            'refundFeeFormulaId': None, 'minRefundFee': 363, 'minEndorseFee': 0, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外免收退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价5％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价5%的退票费，起飞前4小时（不含）内及起飞后需收取票面价10%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None,
            'endorseNote': '允许签转，如变更后承运人适用票价高于国航票价，需补齐票价差额后进行变更，同时收取变更手续费;如变更后承运人适用票价低于国航票价，可按自愿退票办理.如按照自愿变更办理，差额不退，同时收取变更手续费.',
            'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外同等舱位免费更改，起飞前720小时（不含）内至航班起飞前336小时（含）同等舱位免费更改，起飞前336小时（不含）内至起飞前4小时（含）同等舱位免费更改，起飞前4小时（不含）内及起飞后需收取票面价10%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 30, 'luggageType': 1,
         'accumulateMileage': 3405, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 3630, 'serviceCharge': None},
         'babyPolicy': {'price': 730, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': 'CC_QJ', 'beginKeys': ['CC_QJ'],
         'limitPolicy': False},
        {'id': '4605440173', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEY8KIEQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'L', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 700, 'salePrice': 700, 'printPrice': 700, 'fdPrice': 700,
                   'rate': 0.29, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CnEIvQcQrREaAwi8BSIGCPCiBBgEKgMI9BIyBgjwogQYBDgDSgZOb3JtYWxgvQdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgEBTJoBBwjEut8YEAKiAQNORkSwAYCAgMCggYCACLgBAcIBA0FEVQ==',
            'refundFeeFormulaId': None, 'minRefundFee': 630, 'minEndorseFee': 280, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价30%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价60％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价90%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价20%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价35%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价40%的更改费，起飞前4小时（不含）内及起飞后需收取票面价50%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 500, 'extensionFlags': 0, 'extensionFlags2': 576460795387314200, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 700, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': None, 'beginKeys': [], 'limitPolicy': False},
        {'id': '4605440172', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEY2KEHQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'S', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 1190, 'salePrice': 1190, 'printPrice': 1190, 'fdPrice': 1190,
                   'rate': 0.5, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CmoIvAcQrBEaAwimCSIDCKYJKgMI9BIyAwimCTgDSgZOb3JtYWxgvAdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgEBU5oBBwjEut8YEAKiAQJGRLABgICAwICBgIAIuAEBwgEDQURV',
            'refundFeeFormulaId': None, 'minRefundFee': 595, 'minEndorseFee': 357, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价20%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价45％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价50%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价10%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价25%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价30%的更改费，起飞前4小时（不含）内及起飞后需收取票面价40%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 568, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 1210, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': None, 'beginKeys': [], 'limitPolicy': False},
        {'id': '4605440171', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEYwKYIQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'W', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 1360, 'salePrice': 1360, 'printPrice': 1360, 'fdPrice': 1360,
                   'rate': 0.57, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CmoIvAcQrBEaAwjQCiIDCNAKKgMI9BIyAwjQCjgDSgZOb3JtYWxgvAdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgEBV5oBBwjEut8YEAKiAQJGRLABgICAwICBgIAIuAEBwgEDQURV',
            'refundFeeFormulaId': None, 'minRefundFee': 680, 'minEndorseFee': 408, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价20%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价45％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价50%的退票费，起飞前4小时（不含）内及起飞后需收取票面价100%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外收取票面价10%的更改费，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价25%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价30%的更改费，起飞前4小时（不含）内及起飞后需收取票面价40%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': 568, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 1210, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': None, 'beginKeys': [], 'limitPolicy': False},
        {'id': '4605440170', 'transitCabinIds': None, 'combinedCabinIds': None, 'combinedCabinPriorities': None,
         'pid': 'MAgFEAEYwKMJQICAgICAgICACA==', 'cabinClass': 'Y', 'priceClass': 'V1', 'classAreaCode': None,
         'classCodeCombine': None, 'classCodeDesc': None, 'saleType': 'Normal', 'ifFreeDelivery': False,
         'directFlightChannel': '',
         'price': {'compositionPrice': False, 'price': 1520, 'salePrice': 1520, 'printPrice': 1520, 'fdPrice': 1520,
                   'rate': 0.63, 'discount': None, 'serviceCharge': None, 'originalPrice': None, 'discountAmount': None,
                   'discountShowType': 0, 'favorablePrice': 0, 'pcPrice': None}, 'seatCount': 10,
         'provideBillType': 'Itinerary', 'groupType': 'Priority', 'packageOption': None, 'multipleChoiceX': False,
         'packageProduct': False, 'refundEndorse': {
            'rcKey': 'RCKEY|CmsIuwcQqxEaAwjwCyIDCPALKgMI9BIyAwjwCzgDSgZOb3JtYWxguwdqAk5BcgJDQXoDUEVLggEDSEdIigEGQ0ExNTA5kgECVjGaAQcIxLrfGBACogECRkSwAYCAgMCAgYCACLgBAcIBA0FEVQ==',
            'refundFeeFormulaId': None, 'minRefundFee': 456, 'minEndorseFee': 304, 'refundRuleFlag': 'H',
            'refundNote': '航班起飞前720小时（含）外需收取票面价10%的退票费，起飞前720小时（不含）内至航班起飞前336小时（含）需收取票面价25％的退票费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价30%的退票费，起飞前4小时（不含）内及起飞后需收取票面价40%的退票费。（婴儿免收退票费）',
            'endorseRuleFlag': None, 'endorseNote': '不得签转。', 'changeRuleFlag': 'H', 'changeRuleId': None,
            'changeNote': '航班起飞前720小时（含）以外同等舱位免费更改，起飞前720小时（不含）内至航班起飞前336小时（含）收取票价15%的更改费，起飞前336小时（不含）内至起飞前4小时（含）收取票面价20%的更改费，起飞前4小时（不含）内及起飞后需收取票面价30%的更改费。改期费与升舱费同时发生时，需同时收取。（婴儿免收变更费）',
            'remark': None, 'serviceLevel': 2}, 'pcCode': '', 'freeLuggageAmount': 20, 'luggageType': 1,
         'accumulateMileage': -1, 'extensionFlags': 0, 'extensionFlags2': 576460786797379600, 'policyType': 'NA',
         'productType': 'Normal', 'agreementIdList': [],
         'orientThrowPolicy': {'age': '', 'airline': None, 'idCardNo': None, 'membership': None, 'num': None,
                               'specialAgeLimit': 0, 'applySex': None, 'student': 0, 'civs': 0, 'freqFlag': 0},
         'restrictions': {'passengerAgeLimit': '', 'minPassengerNum': 0, 'maxPassengerNum': 0,
                          'acceptableIdCards': None, 'acceptableBank': '', 'acceptablePaymentWays': None,
                          'acceptablePaymentCards': None, 'cardTypeBlacks': None}, 'agreementId': '',
         'productInfoList': ['Normal'], 'applyType': 'NA', 'needApply': False, 'successRate': None,
         'rebateAmount': None, 'rebateCPCity': None, 'floatUpReturnCash': None, 'normalPolicyReturnCash': None,
         'policyReturnMiles': None, 'specialClass': None, 'upgradeCabin': None, 'advertXPackage': None,
         'flyHotel': None, 'hotelLabelDisplay': False, 'marketingCode': None, 'productSource': 3,
         'childInfantBookAdultInfo': None, 'childPolicy': {'price': 1210, 'serviceCharge': None},
         'babyPolicy': {'price': 240, 'serviceCharge': None}, 'infantSoldOut': False, 'businessAircraftInfo': None,
         'displayDefault': False, 'labels': None, 'additionalProductGroups': None, 'gifts': None, 'luggageMerge': False,
         'luggageLimitation': {'carryonLuggageMaxWeight': 5, 'carryonLuggageMaxSize': '55*40*20',
                               'carryonLuggageMaxAmount': 0, 'checkinLuggageMaxWeight': 40,
                               'checkinLuggageMaxSize': '100*60*40', 'checkinLuggageMaxAmount': 1,
                               'luggageSpcefiedDesc': None}, 'ruleRemarks': None, 'additionalRebate': False,
         'additionalRebateAmount': None, 'productAttributes': None, 'compositionPriceRemark': '', 'buyRemainingTime': 0,
         'freeRreCombinationIds': None, 'points': None, 'groupTicketPrice': None, 'scatterGroupPrice': None,
         'single2RoundTotalPrice': 0, 'useContinentPlusN': None, 'key': None, 'beginKeys': [], 'limitPolicy': False}],
      'characteristic': {'flightVirtualInfo': None, 'lowestPrice': 330, 'lowestPriceId': '4605440177',
                         'lowestCfPrice': 2400, 'lowestChildPrice': 550, 'lowestChildCfPrice': 2420,
                         'lowestChildAdultPrice': None, 'lowestChildAdultCfPrice': None, 'lowestBabyPrice': None,
                         'infantSoldOut': False, 'lowestBabyCfPrice': None, 'cfInfantSoldOut': False, 'flyMan': False,
                         'superFlyMan': False, 'flightTypes': None, 'weight': 0, 'businessAircraft': False,
                         'roundTripDiscounts': False, 'groupTicketPrice': None, 'scatterGroupPrice': None,
                         'standardPrices': [{'cabinClass': 'Y', 'price': 2420}, {'cabinClass': 'C', 'price': 7260},
                                            {'cabinClass': 'F', 'price': 8470}], 'discountAmount': None,
                         'discountShowType': 0, 'promotion': False, 'hx': False, 'providerHx': False,
                         'hotFlight': False}}]
